- name: RHEL | Set limits for elasticsearch user
  template:
    src: etc-limits-elasticsearch.conf.j2
    dest: /etc/security/limits.d/elasticsearch.conf
  when: ansible_facts.distribution_major_version is version_compare('6', '=')
  tags:
    - elasticsearch
    - es-config

- name: RHEL | Install elasticsearch repo
  yum_repository:
    file: elasticsearch
    name: elasticsearch-{{ es_major_version }}
    description: Elasticsearch repository for {{ es_major_version }} packages
    baseurl: "{{ es_repo_url }}/yum"
    gpgkey: "{{ es_gpg_key_url }}"
    gpgcheck: yes
    enabled: yes
  tags:
    - elasticsearch
    - es-yum

- name: RHEL | Install Elasticsearch GPG key
  rpm_key:
    key: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    state: present
  tags:
    - elasticsearch
    - es-yum

- name: RHEL | Install elasticsearch
  yum:
    name: elasticsearch{{ '' if es_install_state == 'latest' else '-' ~ es_version ~ '*' }}
    state: "{{ es_install_state }}"
  register: es_install_status
  notify: restart elasticsearch
  tags:
    - elasticsearch

- name: RHEL | Copy elasticsearch system config
  template:
    src: etc-sysconfig-elasticsearch.j2
    dest: /etc/sysconfig/elasticsearch
    owner: root
    group: root
    mode: '0644'
  notify: restart elasticsearch
  tags:
    - elasticsearch
    - es-config
