---
- name: Install packages
  yum: name={{ item }} state=latest
  tags: [ "elasticsearch" , "packages" ]
  with_items:
    - java-1.7.0-openjdk

- name: Install elasticsearch repo
  copy: src=elasticsearch-1.2.repo dest=/etc/yum.repos.d/elasticsearch-1.2.repo owner=root group=root mode=0644
  tags: [ "elasticsearch" , "yum" ]

- name: Copy Elasticsearch GPG key
  copy: src=GPG-KEY-elasticsearch dest=/etc/pki/rpm-gpg/GPG-KEY-elasticsearch owner=root group=root mode=0644
  tags: [ "elasticsearch" , "yum" ]
  notify: install elasticsearch gpg key

- name: Install elasticsearch
  yum: name=elasticsearch state=present
  register: es_install_status
  tags: [ "elasticsearch" , "name" ]

- name: Start and enable elasticsearch
  service: name=elasticsearch enabled=yes state=started
  tags: [ "elasticsearch" , "name" ]

- name: Copy main elasticsearch config
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644
  tags: [ "elasticsearch" , "esconfig" ]
  notify: restart elasticsearch

- name: Copy elasticsearch system config
  template: src=etc-sysconfig-elasticsearch.j2 dest=/etc/sysconfig/elasticsearch owner=root group=root mode=0644
  tags: [ "elasticsearch" , "esconfig" ]
  notify: restart elasticsearch

- name: Create /etc/elasticsearch/scripts
  file: path=/etc/elasticsearch/scripts state=directory owner=root group=root directory_mode=755
  tags: [ 'elasticsearch' , 'esconfig' ]

- name: Copy elasticsearch synthetic field script
  copy: src=kibana dest=/etc/elasticsearch/scripts owner=root group=root mode=0644 directory_mode=755
  tags: [ 'elasticsearch' , 'esconfig' ]

- name: Disable swap in /etc/fstab
  lineinfile: "state=present backup=yes dest=/etc/fstab regexp='(^.*swap.*$)' line='#\\1' backrefs=yes"
  notify: turn off swap
  tags: [ 'elasticsearch' , 'esconfig' ]

- { include: update-plugins.yml, when: es_update_plugins or es_install_status.changed }
