# TODO This may be able to be handeled better by using network.publish_host
# https://www.elastic.co/guide/en/elasticsearch/reference/5.4/modules-network.html#advanced-network-settings
- name: Set es_http_listen_port
  set_fact:
    es_http_listen_port: "{{ es_http_port + 1 }}"
  when: es_ssl_proxy
  tags:
    - always
    - elasticsearch
    - es-config
    - es-nginx
    - es-nginxconfig
    - es-kibana
    - es-kibanaconfig

- name: Get current HTTP port
  shell: "grep http.port {{ es_conf_dir }}/elasticsearch.yml | cut -d ' ' -f 2"
  register: current_es_http_port
  changed_when: no
  tags:
    - always
    - elasticsearch

- name: Include distribution specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always
    - elasticsearch

- name: Include distribution specific tasks
  include: Install-{{ ansible_os_family }}.yml

- name: Copy main elasticsearch config
  template:
    src: elasticsearch.yml.j2
    dest: "{{ es_conf_dir }}/elasticsearch.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart elasticsearch
  tags:
    - elasticsearch
    - es-config

# FIXME
# Seems this could be done more cleanly with replace, but I kept getting errors
# when trying to use a backreference.
- name: Set heap size
  lineinfile:
    dest: "{{ es_conf_dir }}/jvm.options"
    regexp: ^\-{{ item }}.*$
    line: '-{{ item }}{{ es_heap_size }}'
  when: es_major_version | version_compare('5', '>=')
  notify: restart elasticsearch
  with_items:
    - Xms
    - Xmx
  tags:
    - elasticsearch
    - es-config

- name: Start and enable elasticsearch
  service:
    name: elasticsearch
    enabled: yes
    state: started
  tags:
    - elasticsearch

- name: Copy elasticsearch nginx config
  template:
    src: etc-nginx-conf.d-elasticsearch.j2
    dest: "{{ nginx_conf_dir }}/elasticsearch.conf"
    owner: root
    group: root
    mode: 0644
  tags:
    - elasticsearch
    - es-config
    - es-nginx
    - es-nginxconfig
  when: es_ssl_proxy
  notify: reload nginx

- name: Remove elasticsearch nginx config
  file:
    path: "{{ nginx_conf_dir }}/elasticsearch.conf"
    state: absent
  tags:
    - elasticsearch
    - es-config
    - es-nginx
    - es-nginxconfig
  when: not es_ssl_proxy
  notify: reload nginx

- name: Disable swap in /etc/fstab
  lineinfile:
    state: present
    backup: yes
    dest: /etc/fstab
    regexp: '^#?(.*swap.*$)'
    line: '#\1'
    backrefs: yes
  when: es_disable_swap | bool
  notify: turn off swap
  tags:
    - elasticsearch
    - es-config
    - es-swap

- name: Enable swap in /etc/fstab
  lineinfile:
    state: present
    backup: yes
    dest: /etc/fstab
    regexp: '^#+(.*swap.*$)'
    line: '\1'
    backrefs: yes
  when: not es_disable_swap | bool
  notify: turn on swap
  tags:
    - elasticsearch
    - es-config
    - es-swap

# TODO Add template for log4j settings
# https://www.elastic.co/guide/en/elasticsearch/reference/5.4/settings.html#logging

# This extra restart is necessary to prevent the check following tasks from
# failing because they will be looking at the wrong port.
- name: Restart elasticsearch if new HTTP port is different
  service:
    name: elasticsearch
    state: restarted
  when: es_http_listen_port != (current_es_http_port.stdout | int )
  tags:
    - elasticsearch

- name: Wait for elasticsearch HTTP port
  wait_for:
    port: "{{ es_http_listen_port }}"
  tags:
    - elasticsearch

- name: Install plugins
  elasticsearch_plugin:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    plugin_bin: "{{ es_plugin_bin | default(omit) }}"
  with_items: "{{ es_plugins }}"
  tags:
    - elasticsearch
    - es-plugins
