---
- name: Check for elasticsearch plugin
  stat: path=/usr/share/elasticsearch/plugins/{{ item.name }}
  with_items: es_plugins
  register: plugincheck
  tags: [ "elasticsearch" , "esplugins", test ]

- name: Remove elasticsearch plugin
  command:
    ./plugin -remove {{ item.0.install }}
    chdir=/usr/share/elasticsearch/bin
  when: plugincheck is defined and item.1.stat.exists == True
  with_together:
    - es_plugins
    - plugincheck.results
  tags: [ "elasticsearch" , "esplugins" ]

- name: Install elasticsearch plugin
  command:
    ./plugin -install {{ item.install }}
    chdir=/usr/share/elasticsearch/bin
  with_items: es_plugins
  tags: [ "elasticsearch" , "esplugins" ]