---
- name: Check for elasticsearch plugins
  stat:
    path: /usr/share/elasticsearch/plugins/{{ item.name }}
  with_items: "{{ es_plugins }}"
  register: plugincheck
  tags:
    - elasticsearch
    - es-plugins

- name: Remove elasticsearch plugins
  command: ./plugin -remove {{ item.0.name }}
  args:
    chdir: /usr/share/elasticsearch/bin
  when: plugincheck is defined and item.1.stat.exists == True
  with_together:
    - "{{ es_plugins }}"
    - "{{ plugincheck.results }}"
  tags:
    - elasticsearch
    - es-plugins

- name: Install elasticsearch plugins
  command: ./plugin -i {{ item.install }}
  args:
    chdir: /usr/share/elasticsearch/bin
  with_items: "{{ es_plugins }}"
  tags:
    - elasticsearch
    - es-plugins
