# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "chef/centos-6.7"

  (1..3).each do |i|
    config.vm.define "estest-#{i}" do |node|
      node.vm.box = "geerlingguy/centos6"
      node.vm.provider :virtualbox do |vm|
        vm.name = "estest-#{i}"
        vm.memory = 2048
        vm.cpus = 1
      end
      node.vm.hostname = "estest-#{i}"
      node.vm.network "private_network", ip: "10.77.19.1#{i}"
      node.vm.network "forwarded_port", guest: 9200, host: 9201
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
  end

end
