Vagrant.configure(2) do |config|
  config.vm.box = "chef/centos-6.7"

  # CentOS 6
  config.vm.define "es-1" do |node|
    node.vm.box = "samdoran/centos6"
    node.vm.hostname = "es-1"
    node.vm.network "private_network", ip: "10.77.19.11"
    config.vm.provider :virtualbox do |vbox|
      vbox.name = "es-1"
      vbox.memory = 1024
      vbox.cpus = 2
    end
  end

  # CentOS 7
  config.vm.define "es-2" do |node|
    node.vm.box = "samdoran/centos7"
    node.vm.hostname = "es-2"
    node.vm.network "private_network", ip: "10.77.19.12"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "es-2"
      vbox.memory = 1024
      vbox.cpus = 2
    end
  end

  # Ubuntu 16.04
  config.vm.define "es-3" do |node|
    node.vm.box = "geerlingguy/ubuntu1604"
    node.vm.hostname = "es-3"
    node.vm.network "private_network", ip: "10.77.19.13"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "es-3"
      vbox.memory = 1024
      vbox.cpus = 2
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
  end

end
