- name: turn off swap
  command: swapoff -a

- name: turn on swap
  command: swapon -a

- name: restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
    sleep: "{{ '15' if ansible_service_mgr != 'systemd' else omit }}"
  when: not second_restart is changed
