dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint -x 204,306,403,502
  yamllint -c molecule/default/yamllint.yml .
platforms:
  - name: elasticsearch-test
    groups:
      - es
    image: "quay.io/samdoran/${MOLECULE_DISTRIBUTION:-centos7}-ansible:latest"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
scenario:
  name: default
verifier:
  name: ansible
